### ISSUE TITLE
Issue with 'USE_ZLIB'

### ISSUE THREAD

**Issue by gvanem** [webui-dev/webui#259] opened 2023-10-23 09:19 UTC
I just discovered this cool project and built `text-editor.exe` using MSVC/clang-cl.
And it worked just fine!

Now trying to build with `-DUSE_ZLIB`, I get an error from this missing file in `src/civetweb/civetweb.c`:
```c
#if defined(USE_ZLIB)
#include "mod_zlib.inl"
#endif
```

I see in this [Civetweb](https://github.com/civetweb/civetweb/pull/908) PR that it's merged into that project.  
I'm not sure about the relationship between these 2 projects. 

I fixed this by just D/L this `"mod_zlib.inl"` from Civetweb's repo. Perhaps it should be added here too?
Or add Civetweb's repo to a `.gitmodule`?

**Comment by hassandraga** [comment] 2023-10-23 13:32
`ZLIB` is marked as experimental in Civetweb, so we did not include it by default. But I guess it's a good idea to add the `mod_zlib.inl` into `src/civetweb`.

**Comment by gvanem** [comment] 2023-10-24 05:54
Ok. And what about the others like `openssl_dl.inl` and the `mod_lua*.inl` stuff?
I feel something like:
 ```c
#if defined(WEBUI_TLS) || defined(USE_LUA)
#error "An unsupported feature was detected"
#endif
 ```

should be added to `webui.c` since it's rather hard to know what is supported in WebUI or not.

**Comment by hassandraga** [comment] 2023-10-28 22:38
Seriously. Thank you @gvanem, for reporting this. While digging into what features WebUI integrated web server should have... while digging I found how much WebUI will be helpful if we can use it with an external powerful web server like NGINX or Apache, or someone like in your case where you want Civetweb to have a specific feature like ZLIB and Lua.

WebUI, since the first day, was designed to only, and only be used with the internal built-in web server. Now, with this [commit](https://github.com/webui-dev/webui/commit/8363cccc9a6d5d4dd7c1b06c361f8232b21060e2), and also [this one](https://github.com/webui-dev/webui/commit/eb507479705d7b572c682e5aff399be2c10f756b). We can make WebUI use a custom web port, and open a new window with a specific URL. This results in an app that uses NGINX/Apache as a web server for example, while keeping the connection to the back-end using WebUI.

**Example:**

1. Run your preferred web server at any port... 8080 for example
2. Make WebUI use a specific port `webui_set_port(win, 9090)`
3. Add `webui.js` link to your HTML files `http://localhost:9090/webui.js`
4. Show a window at the custom web server address `webui_show(win, "http://localhost:8080/");`

[Full example](https://github.com/webui-dev/webui/tree/main/examples/C/custom_web_server).

**Closed** 2023-10-29 20:55 UTC
