### ISSUE TITLE
`webui_exit` does not work when using a link to navigate a page

### ISSUE THREAD

**Issue by ttytm** [webui-dev/webui#228] opened 2023-09-24 01:21 UTC
`webui_exit` won't work after changing a page through a link, e.g. in the serve a folder example. The window will stay open.
It works when programatically changing the page via the backend.

**Comment by fibodevy** [comment] 2023-09-24 01:33
Thats because `webui.js` is not loaded there. When changing the page the websocket connection drops, on the new page if there is no `<script src="/webui.js">` then it wont reconnect. WebUI cant control the browser and cannot close it, at this point `webui_wait()` returns and browser window remains open.

**Comment by ttytm** [comment] 2023-09-24 01:41
Tho with the `second.html` in the mentioned example, `webui.js` should be included on the page.

https://github.com/webui-dev/webui/blob/main/examples/C/serve_a_folder/second.html

**Comment by ttytm** [comment] 2023-09-24 01:46
One solution would be to state it as a requirement that page navigation inside the webui application requires a programmatic approach from the backend and adjust the example.

**Comment by fibodevy** [comment] 2023-09-24 02:04
Right, in `simple link` exit doesnt work.

I think this has something to do with `bindings`. Both `buttons` call `webui_show()` which I think re-binds to the DOM elements. If direct link is clicked new page is opened directly by the browser and no re-binding by WebUI is done. Events such as clicks are still captured, but `#Exit` element is not binded.

**Comment by fibodevy** [comment] 2023-09-24 02:17
Found the problem. Bindings are ok, that would be weird coz they are in webui.js..

The problem is that the window cant be closed by script if that script didnt open that window. Security measures. And in this case the script (`webui.js`) didnt open the window, you did by clicking the link.

![m35SevnWWq](https://github.com/webui-dev/webui/assets/21068718/0352c2a5-e501-49a0-8ac0-b6f6c12fa206)

Its a bug in the example, not WebUI.

**Comment by ttytm** [comment] 2023-09-24 02:25
> Found the problem. Bindings are ok, that would be weird coz they are in webui.js..
> 
> The problem is that the window cant be closed by script if that script didnt open that window. Security measures. And in this case the script (`webui.js`) didnt open the window, you did by clicking the link.
> 
> ![m35SevnWWq](https://user-images.githubusercontent.com/21068718/270140962-0352c2a5-e501-49a0-8ac0-b6f6c12fa206.png)

Good find!

> WebUI cant control the browser and cannot close it, at this point webui_wait() returns and browser window remains open.

Hmm, maybe it's possible to control it. Since webui already provides an api to get the browser process id, it could end the process on webui_exit.

**Closed** 2023-09-26 22:59 UTC

**Comment by hassandraga** [comment] 2023-09-26 23:04
Thank you for the report. Fixing this issue led to the creation of a new API.

Now, when using all-events `webui_bind(MyWindow, "", events)` WebUI then will block all `href` requests, then the user will receive the event and decide to call `webui_navigate()` or not.

If **no** all-events is used, then everything will work as normal.

**Comment by fibodevy** [comment] 2023-09-27 19:23
@hassandraga can you check if this new feature, catching all hrefs, works on Firefox? In my case it doesnt, on Chrome & Edge it works.

**Comment by hassandraga** [comment] 2023-09-27 19:36
I did not test it in Firefox. I will double-check.
